# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution_ios do
    
  sh "flutter clean"
  sh "flutter pub get"
  sh "flutter build ipa --release --target lib/main_production.dart --no-tree-shake-icons"
  firebase_app_distribution(
      app: ENV['APP_ID'],
      firebase_cli_token: ENV['FIREBASE_CLI_TOKEN'],
      ios_artifact_path: "../build/ios/ipa/Runner.ipa",
      testers: "maha.elshyal@icloud.com",
      release_notes: "First Fastlane Firebase Distribution IPA"
      )
  end
end
    # add actions here: https://docs.fastlane.tools/actions



